bats: Update to v1.12.0.

diff --git a/libexec/bats-core/bats b/libexec/bats-core/bats
--- a/libexec/bats-core/bats
+++ b/libexec/bats-core/bats
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 set -e
 
-export BATS_VERSION='1.9.0'
+export BATS_VERSION='1.12.0'
 VALID_FORMATTERS="pretty, junit, tap, tap13"
 
 version() {
@@ -38,7 +38,7 @@ HELP_TEXT_HEADER
   -c, --count               Count test cases without running any tests
   --code-quote-style <style>
                             A two character string of code quote delimiters
-                            or 'custom' which requires setting $BATS_BEGIN_CODE_QUOTE and 
+                            or 'custom' which requires setting $BATS_BEGIN_CODE_QUOTE and
                             $BATS_END_CODE_QUOTE. Can also be set via $BATS_CODE_QUOTE_STYLE
   --line-reference-format   Controls how file/line references e.g. in stack traces are printed:
                               - comma_line (default): a.bats, line 1
@@ -62,7 +62,8 @@ HELP_TEXT_HEADER
                             Gather the output of failing *and* passing tests
                             as files in directory (if existing, must be empty)
   -h, --help                Display this help message
-  -j, --jobs <jobs>         Number of parallel jobs (requires GNU parallel)
+  -j, --jobs <jobs>         Number of parallel jobs (requires GNU parallel or shenwei356/rush)
+  --parallel-binary-name    Name of parallel binary
   --no-tempdir-cleanup      Preserve test output temporary directory
   --no-parallelize-across-files
                             Serialize test file execution instead of running
@@ -112,7 +113,6 @@ BATS_LIBEXEC="$(
 )"
 export BATS_LIBEXEC
 export BATS_CWD="$PWD"
-export BATS_TEST_FILTER=
 export PATH="$BATS_LIBEXEC:$PATH"
 export BATS_ROOT_PID=$$
 export BATS_TMPDIR="${TMPDIR:-/tmp}"
@@ -133,6 +133,9 @@ fi
 
 arguments=()
 
+# list of single char options that don't expect a value
+single_char_flags="hvcprtTx"
+
 # Unpack single-character options bundled together, e.g. -cr, -pr.
 for arg in "$@"; do
   if [[ "$arg" =~ ^-[^-]. ]]; then
@@ -140,6 +143,11 @@ for arg in "$@"; do
     while option="${arg:$((index++)):1}"; do
       if [[ -z "$option" ]]; then
         break
+      fi
+      if [[ "$single_char_flags" != *$option* && -n "${arg:index}" ]]; then
+        printf "Error: -%s is not allowed within pack of flags.\n" "$option"
+        printf "       Please put it last (e.g. \`-rF junit\` instead of \`-Fr junit\`), or on its own (\`-r -F junit\`)!\n"
+        exit 1
       fi
       arguments+=("-$option")
     done
@@ -211,6 +219,10 @@ while [[ "$#" -ne 0 ]]; do
   -j | --jobs)
     shift
     flags+=('-j' "$1")
+    ;;
+  --parallel-binary-name)
+    shift
+    flags+=('--parallel-binary-name' "$1")
     ;;
   -r | --recursive)
     recursive=1
@@ -473,7 +485,7 @@ if [[ -n "$setup_suite_file" ]]; then
 fi
 
 # shellcheck source=lib/bats-core/validator.bash
-source "$BATS_ROOT/lib/bats-core/validator.bash"
+source "$BATS_ROOT/$BATS_LIBDIR/bats-core/validator.bash"
 
 trap 'BATS_INTERRUPTED=true' INT # let the lower levels handle the interruption
 
diff --git a/libexec/bats-core/bats-exec-test b/libexec/bats-core/bats-exec-test
--- a/libexec/bats-core/bats-exec-test
+++ b/libexec/bats-core/bats-exec-test
@@ -72,16 +72,18 @@ bats_create_test_tmpdirs() {
     exit 1
   fi
 
-  printf "%s\n" "$BATS_TEST_NAME" >"$BATS_TEST_TMPDIR.name"
+  printf "%s\n" "$BATS_TEST_NAME" >> "$BATS_TEST_TMPDIR.name" # append name in case of test retries
 
   export BATS_TEST_TMPDIR
 }
 
 # load the test helper functions like `load` or `run` that are needed to run a (preprocessed) .bats file without bash errors
 # shellcheck source=lib/bats-core/test_functions.bash disable=SC2153
-source "$BATS_ROOT/lib/bats-core/test_functions.bash"
+source "$BATS_ROOT/$BATS_LIBDIR/bats-core/test_functions.bash"
+_bats_test_functions_setup "$BATS_TEST_NUMBER"
+
 # shellcheck source=lib/bats-core/tracing.bash disable=SC2153
-source "$BATS_ROOT/lib/bats-core/tracing.bash"
+source "$BATS_ROOT/$BATS_LIBDIR/bats-core/tracing.bash"
 
 bats_teardown_trap() {
   bats_check_status_from_trap
@@ -89,8 +91,10 @@ bats_teardown_trap() {
 
   # `bats_teardown_trap` is always called with one parameter (BATS_TEARDOWN_STARTED)
   # The second parameter is optional and corresponds for to the killer pid
-  # that will be forwarded to the exit trap to kill it if necesary
+  # that will be forwarded to the exit trap to kill it if necessary
   local killer_pid=${2:-}
+
+  bats_set_stacktrace_limit
 
   # mark the start of this function to distinguish where skip is called
   # parameter 1 will signify the reason why this function was called
@@ -109,7 +113,7 @@ bats_teardown_trap() {
 }
 
 # shellcheck source=lib/bats-core/common.bash
-source "$BATS_ROOT/lib/bats-core/common.bash"
+source "$BATS_ROOT/$BATS_LIBDIR/bats-core/common.bash"
 
 bats_exit_trap() {
   local status
@@ -132,7 +136,8 @@ bats_exit_trap() {
 
   BATS_TEST_TIME=''
   if [[ -n "$BATS_ENABLE_TIMING" ]]; then
-    BATS_TEST_TIME=" in "$(($(get_mills_since_epoch) - BATS_TEST_START_TIME))"ms"
+    get_mills_since_epoch BATS_TEST_END_TIME
+    BATS_TEST_TIME=" in "$((BATS_TEST_END_TIME - BATS_TEST_START_TIME))"ms"
   fi
 
   local print_bats_out="${BATS_SHOW_OUTPUT_OF_SUCCEEDING_TESTS}"
@@ -157,6 +162,11 @@ bats_exit_trap() {
       rm -r "$BATS_TEST_TMPDIR" # clean up for retry
     else
       printf 'not ok %d %s%s\n' "$BATS_SUITE_TEST_NUMBER" "${BATS_TEST_NAME_PREFIX:-}${BATS_TEST_DESCRIPTION}${BATS_TEST_TIME}" "$exit_metadata" >&3
+      if (( ${#BATS_TEST_TAGS[@]} > 0 )); then
+        printf '# tags:'
+        printf ' %s' "${BATS_TEST_TAGS[@]}"
+        printf '\n'
+      fi >&3
       local stack_trace
       bats_get_failure_stack_trace stack_trace
       bats_print_stack_trace "${stack_trace[@]}" >&3
@@ -194,7 +204,7 @@ bats_exit_trap() {
     if [[ -n "$should_retry" ]]; then
       try_suffix="-try$BATS_TEST_TRY_NUMBER"
     fi
-    cp "$BATS_OUT" "$BATS_GATHER_TEST_OUTPUTS_IN/$BATS_SUITE_TEST_NUMBER$try_suffix-$BATS_TEST_DESCRIPTION.log"
+    cp "$BATS_OUT" "$BATS_GATHER_TEST_OUTPUTS_IN/$BATS_SUITE_TEST_NUMBER$try_suffix-${BATS_TEST_DESCRIPTION//\//%2F}.log"
   fi
   rm -f "$BATS_OUT"
   exit "$status"
@@ -263,7 +273,7 @@ bats_start_timeout_countdown() { # <timeout>
   # Start another process to kill the children of this process
   (
     sleep "$timeout" &
-    # sleep won't recieve signals, so we use wait below
+    # sleep won't receive signals, so we use wait below
     # and kill sleep explicitly when signalled to do so
     # shellcheck disable=SC2064
     trap "kill $!; exit 0" ABRT
@@ -280,20 +290,31 @@ bats_abort_timeout_countdown() {
   kill -ABRT "$1" &>/dev/null || true
 }
 
-get_mills_since_epoch() {
+
+if [[ -n "${EPOCHREALTIME-}"  ]]; then
+get_mills_since_epoch() { # <output-variable>
+  local -r output_variable="$1"
+  local int frac
+  # allow for different decimal separators
+  IFS=., read -r int frac <<<"$EPOCHREALTIME"
+  printf -v "$output_variable" "%d" "${int}${frac::3}"
+}
+else
+get_mills_since_epoch() { # <output-variable>
+  local -r output_variable="$1"
   local ms_since_epoch
-  ms_since_epoch=$(date +%s%N)
+  ms_since_epoch=$(bats_execute date +%s%N)
   if [[ "$ms_since_epoch" == *N || "${#ms_since_epoch}" -lt 19 ]]; then
-    ms_since_epoch=$(($(date +%s) * 1000))
+    ms_since_epoch=$(($(bats_execute date +%s) * 1000))
   else
     ms_since_epoch=$((ms_since_epoch / 1000000))
   fi
-
-  printf "%d\n" "$ms_since_epoch"
+  printf -v "$output_variable" "%d" "$ms_since_epoch"
 }
+fi
 
 bats_perform_test() {
-  if ! declare -F "$BATS_TEST_NAME" &>/dev/null; then
+  if ! declare -F "${BATS_TEST_NAME%% *}" &>/dev/null; then
     local quoted_test_name
     bats_quote_code quoted_test_name "$BATS_TEST_NAME"
     printf "bats: unknown test name %s\n" "$quoted_test_name" >&2
@@ -323,8 +344,16 @@ bats_perform_test() {
   # shellcheck disable=SC2064
   trap "bats_teardown_trap as-exit-trap $BATS_killer_pid" EXIT
 
-  BATS_TEST_START_TIME=$(get_mills_since_epoch)
-  "$BATS_TEST_NAME" >>"$BATS_OUT" 2>&1 4>&1
+  if [[ -n "$BATS_EXTENDED_SYNTAX" ]]; then
+    printf 'begin %d %s\n' "$BATS_SUITE_TEST_NUMBER" "${BATS_TEST_NAME_PREFIX:-}$BATS_TEST_DESCRIPTION" >&3
+  fi
+
+  get_mills_since_epoch BATS_TEST_START_TIME
+  {
+    bats_set_stacktrace_limit
+    setup "$@"
+    "$@"
+  } >>"$BATS_OUT" 2>&1 4>&1
 
   BATS_TEST_COMPLETED=1
   # shellcheck disable=SC2064
@@ -335,11 +364,15 @@ bats_perform_test() {
 trap bats_interrupt_trap INT
 
 # shellcheck source=lib/bats-core/preprocessing.bash
-source "$BATS_ROOT/lib/bats-core/preprocessing.bash"
+source "$BATS_ROOT/$BATS_LIBDIR/bats-core/preprocessing.bash"
 
 exec 3<&1
+BATS_OUT="$BATS_RUN_TMPDIR/test/$BATS_SUITE_TEST_NUMBER.out"
 
 bats_create_test_tmpdirs
-# Run the given test.
 bats_evaluate_preprocessed_source
-bats_perform_test
+
+readonly BATS_TEST_TAGS
+
+# use eval to parse (internally quoted!) test command into parameters
+bats_perform_test "${BATS_TEST_COMMAND[@]}"
