Upgrade bats to v1.9.0.

diff --git a/libexec/bats-core/bats b/libexec/bats-core/bats
--- a/libexec/bats-core/bats
+++ b/libexec/bats-core/bats
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 set -e
 
-export BATS_VERSION='1.3.0'
+export BATS_VERSION='1.9.0'
 VALID_FORMATTERS="pretty, junit, tap, tap13"
 
 version() {
@@ -9,8 +9,15 @@ version() {
 }
 
 abort() {
+  local print_usage=1
+  if [[ ${1:-} == --no-print-usage ]]; then
+    print_usage=
+    shift
+  fi
   printf 'Error: %s\n' "$1" >&2
-  usage >&2
+  if [[ -n $print_usage ]]; then
+    usage >&2
+  fi
   exit 1
 }
 
@@ -29,9 +36,31 @@ HELP_TEXT_HEADER
   containing Bats test files (ending with ".bats")
 
   -c, --count               Count test cases without running any tests
+  --code-quote-style <style>
+                            A two character string of code quote delimiters
+                            or 'custom' which requires setting $BATS_BEGIN_CODE_QUOTE and 
+                            $BATS_END_CODE_QUOTE. Can also be set via $BATS_CODE_QUOTE_STYLE
+  --line-reference-format   Controls how file/line references e.g. in stack traces are printed:
+                              - comma_line (default): a.bats, line 1
+                              - colon:  a.bats:1
+                              - uri: file:///tests/a.bats:1
+                              - custom: provide your own via defining bats_format_file_line_reference_custom
+                                        with parameters <filename> <line>, store via `printf -v "$output"`
   -f, --filter <regex>      Only run tests that match the regular expression
+  --filter-status <status>  Only run tests with the given status in the last completed (no CTRL+C/SIGINT) run.
+                            Valid <status> values are:
+                              failed - runs tests that failed or were not present in the last run
+                              missed - runs tests that were not present in the last run
+  --filter-tags <comma-separated-tag-list>
+                            Only run tests that match all the tags in the list (&&).
+                            You can negate a tag via prepending '!'.
+                            Specifying this flag multiple times allows for logical or (||):
+                            `--filter-tags A,B --filter-tags A,!C` matches tags (A && B) || (A && !C)
   -F, --formatter <type>    Switch between formatters: pretty (default),
-                              tap (default w/o term), tap13, junit
+                              tap (default w/o term), tap13, junit, /<absolute path to formatter>
+  --gather-test-outputs-in <directory>
+                            Gather the output of failing *and* passing tests
+                            as files in directory (if existing, must be empty)
   -h, --help                Display this help message
   -j, --jobs <jobs>         Number of parallel jobs (requires GNU parallel)
   --no-tempdir-cleanup      Preserve test output temporary directory
@@ -42,11 +71,16 @@ HELP_TEXT_HEADER
                             Serialize test execution within files instead of
                             running them in parallel (requires --jobs >1)
   --report-formatter <type> Switch between reporters (same options as --formatter)
-  -o, --output <dir>        Directory to write report files
+  -o, --output <dir>        Directory to write report files (must exist)
   -p, --pretty              Shorthand for "--formatter pretty"
+  --print-output-on-failure Automatically print the value of `$output` on failed tests
   -r, --recursive           Include tests in subdirectories
+  --show-output-of-passing-tests
+                            Print output of passing tests
   -t, --tap                 Shorthand for "--formatter tap"
   -T, --timing              Add timing information to tests
+  -x, --trace               Print test commands as they are executed (like `set -x`)
+  --verbose-run             Make `run` print `$output` by default
   -v, --version             Display the version number
 
   For more information, see https://github.com/bats-core/bats-core
@@ -56,7 +90,11 @@ HELP_TEXT_BODY
 expand_path() {
   local path="${1%/}"
   local dirname="${path%/*}"
+  if [[ -z "$dirname" ]]; then
+    dirname=/
+  fi
   local result="$2"
+  local OLDPWD="$PWD"
 
   if [[ "$dirname" == "$path" ]]; then
     dirname="$PWD"
@@ -68,20 +106,30 @@ expand_path() {
   printf -v "$result" '%s/%s' "$dirname" "${path##*/}"
 }
 
-BATS_LIBEXEC="$(dirname "$(bats_readlinkf "${BASH_SOURCE[0]}")")"
+BATS_LIBEXEC="$(
+  cd "$(dirname "$(bats_readlinkf "${BASH_SOURCE[0]}")")"
+  pwd
+)"
 export BATS_LIBEXEC
 export BATS_CWD="$PWD"
-export BATS_TEST_PATTERN="^[[:blank:]]*@test[[:blank:]]+(.*[^[:blank:]])[[:blank:]]+\{(.*)\$"
-export BATS_TEST_PATTERN_COMMENT="[[:blank:]]*([^[:blank:]()]+)[[:blank:]]*\(?\)?[[:blank:]]+\{[[:blank:]]+#[[:blank:]]*@test[[:blank:]]*\$"
 export BATS_TEST_FILTER=
 export PATH="$BATS_LIBEXEC:$PATH"
 export BATS_ROOT_PID=$$
-if [[ -z "${TMPDIR-}" ]]; then
-  export BATS_TMPDIR="/tmp"
-else
-  export BATS_TMPDIR="${TMPDIR%/}"
+export BATS_TMPDIR="${TMPDIR:-/tmp}"
+BATS_TMPDIR=${BATS_TMPDIR%/} # chop off trailing / to avoid duplication
+export BATS_RUN_TMPDIR=
+export BATS_GUARANTEED_MINIMUM_VERSION=0.0.0
+export BATS_LIB_PATH=${BATS_LIB_PATH-/usr/lib/bats}
+BATS_REPORT_OUTPUT_DIR=${BATS_REPORT_OUTPUT_DIR-.}
+export BATS_LINE_REFERENCE_FORMAT=${BATS_LINE_REFERENCE_FORMAT-comma_line}
+
+if [[ ! -d "${BATS_TMPDIR}" ]]; then
+  printf "Error: BATS_TMPDIR (%s) does not exist or is not a directory" "${BATS_TMPDIR}" >&2
+  exit 1
+elif [[ ! -w "${BATS_TMPDIR}" ]]; then
+  printf "Error: BATS_TMPDIR (%s) is not writable" "${BATS_TMPDIR}" >&2
+  exit 1
 fi
-export BATS_RUN_TMPDIR="$BATS_TMPDIR/bats-run-$BATS_ROOT_PID"
 
 arguments=()
 
@@ -105,13 +153,13 @@ set -- "${arguments[@]}"
 arguments=()
 
 unset flags recursive formatter_flags
-flags=('--dummy-flag') # add a dummy flag to prevent unset varialeb errors on empty array expansion in old bash versions
-formatter_flags=('--dummy-flag') # add a dummy flag to prevent unset varialeb errors on empty array expansion in old bash versions
-formatter='tap'
+flags=('--dummy-flag')           # add a dummy flag to prevent unset variable errors on empty array expansion in old bash versions
+formatter_flags=('--dummy-flag') # add a dummy flag to prevent unset variable errors on empty array expansion in old bash versions
+formatter=${BATS_FORMATTER:-'tap'}
 report_formatter=''
 recursive=
+setup_suite_file=''
 export BATS_TEMPDIR_CLEANUP=1
-output=
 if [[ -z "${CI:-}" && -t 0 && -t 1 ]] && command -v tput >/dev/null; then
   formatter='pretty'
 fi
@@ -137,7 +185,7 @@ while [[ "$#" -ne 0 ]]; do
   -F | --formatter)
     shift
     # allow cat formatter to see extended output but don't advertise to users
-    if [[ $1 =~ ^(pretty|junit|tap|tap13|cat)$ ]]; then
+    if [[ $1 =~ ^(pretty|junit|tap|tap13|cat|/.*)$ ]]; then
       formatter="$1"
     else
       printf "Unknown formatter '%s', valid options are %s\n" "$1" "${VALID_FORMATTERS}"
@@ -146,7 +194,7 @@ while [[ "$#" -ne 0 ]]; do
     ;;
   --report-formatter)
     shift
-    if [[ $1 =~ ^(pretty|junit|tap|tap13)$ ]]; then
+    if [[ $1 =~ ^(cat|pretty|junit|tap|tap13|/.*)$ ]]; then
       report_formatter="$1"
     else
       printf "Unknown report formatter '%s', valid options are %s\n" "$1" "${VALID_FORMATTERS}"
@@ -155,7 +203,7 @@ while [[ "$#" -ne 0 ]]; do
     ;;
   -o | --output)
     shift
-    output="$1"
+    BATS_REPORT_OUTPUT_DIR="$1"
     ;;
   -p | --pretty)
     formatter='pretty'
@@ -175,8 +223,8 @@ while [[ "$#" -ne 0 ]]; do
     formatter_flags+=('-T')
     ;;
   # this flag is now a no-op, as it is the parallel default
-  --parallel-preserve-environment)
-    ;;
+  --parallel-preserve-environment) ;;
+
   --no-parallelize-across-files)
     flags+=("--no-parallelize-across-files")
     ;;
@@ -190,6 +238,50 @@ while [[ "$#" -ne 0 ]]; do
     BATS_RUN_TMPDIR="$2"
     shift
     ;;
+  -x | --trace)
+    flags+=(--trace)
+    ;;
+  --print-output-on-failure)
+    flags+=(--print-output-on-failure)
+    ;;
+  --show-output-of-passing-tests)
+    flags+=(--show-output-of-passing-tests)
+    ;;
+  --verbose-run)
+    flags+=(--verbose-run)
+    ;;
+  --gather-test-outputs-in)
+    shift
+    output_dir="$1"
+    if [ -d "$output_dir" ]; then
+      if ! find "$output_dir" -mindepth 1 -exec false {} + 2>/dev/null; then
+        abort --no-print-usage "Directory '$output_dir' must be empty for --gather-test-outputs-in"
+      fi
+    elif ! mkdir "$output_dir" 2>/dev/null; then
+      abort --no-print-usage "Could not create '$output_dir' for --gather-test-outputs-in"
+    fi
+    flags+=(--gather-test-outputs-in "$output_dir")
+    ;;
+  --setup-suite-file)
+    shift
+    setup_suite_file="$1"
+    ;;
+  --code-quote-style)
+    shift
+    BATS_CODE_QUOTE_STYLE="$1"
+    ;;
+  --filter-status)
+    shift
+    flags+=('--filter-status' "$1")
+    ;;
+  --filter-tags)
+    shift
+    flags+=('--filter-tags' "$1")
+    ;;
+  --line-reference-format)
+    shift
+    BATS_LINE_REFERENCE_FORMAT=$1
+    ;;
   -*)
     abort "Bad command line option '$1'"
     ;;
@@ -200,15 +292,46 @@ while [[ "$#" -ne 0 ]]; do
   shift
 done
 
-if [[ -d "$BATS_RUN_TMPDIR" ]]; then
-  printf "Error: BATS_RUN_TMPDIR (%s) already exists\n" "$BATS_RUN_TMPDIR" >&2
-  printf "Reusing old run directories can lead to unexpected results ... aborting!\n" >&2
+if [[ ! $BATS_LINE_REFERENCE_FORMAT =~ (custom|comma_line|colon|uri) ]]; then
+  abort "Invalid BATS_LINE_REFERENCE_FORMAT '$BATS_LINE_REFERENCE_FORMAT' (e.g. via --line-reference-format)"
+fi
+
+if [[ -n "${BATS_RUN_TMPDIR:-}" ]]; then
+  if [[ -d "$BATS_RUN_TMPDIR" ]]; then
+    printf "Error: BATS_RUN_TMPDIR (%s) already exists\n" "$BATS_RUN_TMPDIR" >&2
+    printf "Reusing old run directories can lead to unexpected results ... aborting!\n" >&2
+    exit 1
+  elif ! mkdir -p "$BATS_RUN_TMPDIR"; then
+    printf "Error: Failed to create BATS_RUN_TMPDIR (%s)\n" "$BATS_RUN_TMPDIR" >&2
+    exit 1
+  fi
+elif ! BATS_RUN_TMPDIR=$(mktemp -d "${BATS_TMPDIR}/bats-run-XXXXXX"); then
+  printf "Error: Failed to create BATS_RUN_TMPDIR (%s) with mktemp\n" "${BATS_TMPDIR}/bats-run-XXXXXX" >&2
   exit 1
 fi
-mkdir -p "$BATS_RUN_TMPDIR"
-if [[ -n "$BATS_TEMPDIR_CLEANUP" ]]; then
-  trap 'rm -rf "$BATS_RUN_TMPDIR"' ERR EXIT
-fi
+
+export BATS_WARNING_FILE="${BATS_RUN_TMPDIR}/warnings.log"
+
+bats_exit_trap() {
+  if [[ -s "$BATS_WARNING_FILE" ]]; then
+    local pre_cat='' post_cat=''
+    if [[ $formatter == pretty ]]; then
+      pre_cat=$'\x1B[31m'
+      post_cat=$'\x1B[0m'
+    fi
+    printf "\nThe following warnings were encountered during tests:\n%s" "$pre_cat"
+    cat "$BATS_WARNING_FILE"
+    printf "%s" "$post_cat"
+  fi >&2
+
+  if [[ -n "$BATS_TEMPDIR_CLEANUP" ]]; then
+    rm -rf "$BATS_RUN_TMPDIR"
+  else
+    printf "BATS_RUN_TMPDIR: %s\n" "$BATS_RUN_TMPDIR" >&2
+  fi
+}
+
+trap bats_exit_trap EXIT
 
 if [[ "$formatter" != "tap" ]]; then
   flags+=('-x')
@@ -227,9 +350,31 @@ if [[ "$report_formatter" == "junit" ]]; then
   report_formatter_flags+=('--base-path' "${arguments[0]}")
 fi
 
+if [[ "$formatter" == "pretty" ]]; then
+  formatter_flags+=('--base-path' "${arguments[0]}")
+fi
+
 # if we don't need to filter extended syntax, use the faster formatter
 if [[ "$formatter" == tap && -z "$report_formatter" ]]; then
   formatter="cat"
+fi
+
+bats_check_formatter() { # <formatter-path>
+  local -r formatter="$1"
+  if [[ ! -f "$formatter" ]]; then
+    printf "ERROR: Formatter '%s' is not readable!\n" "$formatter"
+    exit 1
+  elif [[ ! -x "$formatter" ]]; then
+    printf "ERROR: Formatter '%s' is not executable!\n" "$formatter"
+    exit 1
+  fi
+}
+
+if [[ $formatter == /* ]]; then # absolute paths are direct references to formatters
+  bats_check_formatter "$formatter"
+  interpolated_formatter="$formatter"
+else
+  interpolated_formatter="bats-format-${formatter}"
 fi
 
 if [[ "${#arguments[@]}" -eq 0 ]]; then
@@ -237,33 +382,74 @@ if [[ "${#arguments[@]}" -eq 0 ]]; then
 fi
 
 if [[ -n "$report_formatter" ]]; then
-  # default to the current directory for output
-  if [[ -z "$output" ]]; then
-    output=.
+  if [[ ! -w "${BATS_REPORT_OUTPUT_DIR}" ]]; then
+    abort "Output path ${BATS_REPORT_OUTPUT_DIR} is not writeable"
   fi
-  case "$report_formatter" in
-    tap|tap13)
-      BATS_REPORT_FILE_NAME="report.tap"
+  # only set BATS_REPORT_FILENAME if none was given
+  if [[ -z "${BATS_REPORT_FILENAME:-}" ]]; then
+    case "$report_formatter" in
+    tap | tap13)
+      BATS_REPORT_FILENAME="report.tap"
       ;;
     junit)
-      BATS_REPORT_FILE_NAME="report.xml"
+      BATS_REPORT_FILENAME="report.xml"
       ;;
-    pretty)
-      BATS_REPORT_FILE_NAME="report.log"
+    *)
+      BATS_REPORT_FILENAME="report.log"
       ;;
-  esac
+    esac
+  fi
 fi
 
-if [[ -n "$output" ]]; then
-  if [[ ! -w "${output}" ]]; then
-    abort "Output path ${output} is not writeable"
+if [[ $report_formatter == /* ]]; then # absolute paths are direct references to formatters
+  bats_check_formatter "$report_formatter"
+  interpolated_report_formatter="${report_formatter}"
+else
+  interpolated_report_formatter="bats-format-${report_formatter}"
+fi
+
+if [[ "${BATS_CODE_QUOTE_STYLE-BATS_CODE_QUOTE_STYLE_UNSET}" == BATS_CODE_QUOTE_STYLE_UNSET ]]; then
+  BATS_CODE_QUOTE_STYLE="\`'"
+fi
+
+case "${BATS_CODE_QUOTE_STYLE}" in
+??)
+  BATS_BEGIN_CODE_QUOTE="${BATS_CODE_QUOTE_STYLE::1}"
+  BATS_END_CODE_QUOTE="${BATS_CODE_QUOTE_STYLE:1:1}"
+  export BATS_BEGIN_CODE_QUOTE BATS_END_CODE_QUOTE
+  ;;
+custom)
+  if [[ ${BATS_BEGIN_CODE_QUOTE-BATS_BEGIN_CODE_QUOTE_UNSET} == BATS_BEGIN_CODE_QUOTE_UNSET ||
+    ${BATS_END_CODE_QUOTE-BATS_BEGIN_CODE_QUOTE_UNSET} == BATS_BEGIN_CODE_QUOTE_UNSET ]]; then
+    printf "ERROR: BATS_CODE_QUOTE_STYLE=custom requires BATS_BEGIN_CODE_QUOTE and BATS_END_CODE_QUOTE to be set\n" >&2
+    exit 1
   fi
-  export BATS_REPORT_OUTPUT_PATH="$output"
+  ;;
+*)
+  printf "ERROR: Unknown BATS_CODE_QUOTE_STYLE: %s\n" "$BATS_CODE_QUOTE_STYLE" >&2
+  exit 1
+  ;;
+esac
+
+if [[ -n "$setup_suite_file" && ! -f "$setup_suite_file" ]]; then
+  abort "--setup-suite-file $setup_suite_file does not exist!"
 fi
 
 filenames=()
 for filename in "${arguments[@]}"; do
   expand_path "$filename" 'filename'
+
+  if [[ -z "$setup_suite_file" ]]; then
+    if [[ -d "$filename" ]]; then
+      dirname="$filename"
+    else
+      dirname="${filename%/*}"
+    fi
+    potential_setup_suite_file="$dirname/setup_suite.bash"
+    if [[ -e "$potential_setup_suite_file" ]]; then
+      setup_suite_file="$potential_setup_suite_file"
+    fi
+  fi
 
   if [[ -d "$filename" ]]; then
     shopt -s nullglob
@@ -282,13 +468,37 @@ for filename in "${arguments[@]}"; do
   fi
 done
 
+if [[ -n "$setup_suite_file" ]]; then
+  flags+=("--setup-suite-file" "$setup_suite_file")
+fi
+
 # shellcheck source=lib/bats-core/validator.bash
 source "$BATS_ROOT/lib/bats-core/validator.bash"
 
+trap 'BATS_INTERRUPTED=true' INT # let the lower levels handle the interruption
+
 set -o pipefail execfail
 
+# pipe stdin into command and to stdout
+# pipe command stdout to file
+bats_tee() { # <output-file> <command...>
+  local output_file=$1 status=0
+  shift
+  exec 3<&1 # use FD3 to get around pipe
+  tee >(cat >&3) | "$@" >"$output_file" || status=$?
+  if (( status != 0 )); then
+    printf "ERROR: command \`%s\` failed with status %d\n" "$*" "$status" >&2
+  fi
+  return $status
+}
+
 if [[ -n "$report_formatter" ]]; then
-  exec bats-exec-suite "${flags[@]}" "${filenames[@]}" | tee >("bats-format-${report_formatter}" "${report_formatter_flags[@]}" >"${BATS_REPORT_OUTPUT_PATH}/${BATS_REPORT_FILE_NAME}") | bats_test_count_validator | "bats-format-${formatter}" "${formatter_flags[@]}"
+  exec bats-exec-suite "${flags[@]}" "${filenames[@]}" |
+    bats_tee "${BATS_REPORT_OUTPUT_DIR}/${BATS_REPORT_FILENAME}" "$interpolated_report_formatter" "${report_formatter_flags[@]}" |
+    bats_test_count_validator |
+    "$interpolated_formatter" "${formatter_flags[@]}"
 else
-  exec bats-exec-suite "${flags[@]}" "${filenames[@]}" | bats_test_count_validator | "bats-format-${formatter}" "${formatter_flags[@]}"
+  exec bats-exec-suite "${flags[@]}" "${filenames[@]}" |
+    bats_test_count_validator |
+    "$interpolated_formatter" "${formatter_flags[@]}"
 fi
diff --git a/libexec/bats-core/bats-exec-test b/libexec/bats-core/bats-exec-test
--- a/libexec/bats-core/bats-exec-test
+++ b/libexec/bats-core/bats-exec-test
@@ -2,29 +2,41 @@
 set -eET
 
 # Variables used in other scripts.
-BATS_COUNT_ONLY=''
-BATS_TEST_FILTER=''
 BATS_ENABLE_TIMING=''
 BATS_EXTENDED_SYNTAX=''
+BATS_TRACE_LEVEL="${BATS_TRACE_LEVEL:-0}"
+BATS_PRINT_OUTPUT_ON_FAILURE="${BATS_PRINT_OUTPUT_ON_FAILURE:-}"
+BATS_SHOW_OUTPUT_OF_SUCCEEDING_TESTS="${BATS_SHOW_OUTPUT_OF_SUCCEEDING_TESTS:-}"
+BATS_VERBOSE_RUN="${BATS_VERBOSE_RUN:-}"
+BATS_GATHER_TEST_OUTPUTS_IN="${BATS_GATHER_TEST_OUTPUTS_IN:-}"
+BATS_TEST_NAME_PREFIX="${BATS_TEST_NAME_PREFIX:-}"
 
 while [[ "$#" -ne 0 ]]; do
   case "$1" in
-  -c)
-    # shellcheck disable=SC2034
-    BATS_COUNT_ONLY=1
-    ;;
-  -f)
-    shift
-    # shellcheck disable=SC2034
-    BATS_TEST_FILTER="$1"
-    ;;
   -T)
     BATS_ENABLE_TIMING='-T'
-    BATS_PERFORM_TEST_CMD+=('-T')
     ;;
   -x)
     # shellcheck disable=SC2034
     BATS_EXTENDED_SYNTAX='-x'
+    ;;
+  --dummy-flag) ;;
+
+  --trace)
+    ((++BATS_TRACE_LEVEL)) # avoid returning 0
+    ;;
+  --print-output-on-failure)
+    BATS_PRINT_OUTPUT_ON_FAILURE=1
+    ;;
+  --show-output-of-passing-tests)
+    BATS_SHOW_OUTPUT_OF_SUCCEEDING_TESTS=1
+    ;;
+  --verbose-run)
+    BATS_VERBOSE_RUN=1
+    ;;
+  --gather-test-outputs-in)
+    shift
+    BATS_GATHER_TEST_OUTPUTS_IN="$1"
     ;;
   *)
     break
@@ -33,8 +45,12 @@ while [[ "$#" -ne 0 ]]; do
   shift
 done
 
-BATS_TEST_FILENAME="$1"
-shift
+export BATS_TEST_FILENAME="$1"
+export BATS_TEST_NAME="$2"
+export BATS_SUITE_TEST_NUMBER="$3"
+export BATS_TEST_NUMBER="$4"
+BATS_TEST_TRY_NUMBER="$5"
+
 if [[ -z "$BATS_TEST_FILENAME" ]]; then
   printf 'usage: bats-exec-test <filename>\n' >&2
   exit 1
@@ -43,6 +59,24 @@ elif [[ ! -f "$BATS_TEST_FILENAME" ]]; then
   exit 1
 fi
 
+bats_create_test_tmpdirs() {
+  local tests_tmpdir="${BATS_RUN_TMPDIR}/test"
+  if ! mkdir -p "$tests_tmpdir"; then
+    printf 'Failed to create: %s\n' "$tests_tmpdir" >&2
+    exit 1
+  fi
+
+  BATS_TEST_TMPDIR="$tests_tmpdir/$BATS_SUITE_TEST_NUMBER"
+  if ! mkdir "$BATS_TEST_TMPDIR"; then
+    printf 'Failed to create BATS_TEST_TMPDIR%d: %s\n' "$BATS_TEST_TRY_NUMBER" "$BATS_TEST_TMPDIR" >&2
+    exit 1
+  fi
+
+  printf "%s\n" "$BATS_TEST_NAME" >"$BATS_TEST_TMPDIR.name"
+
+  export BATS_TEST_TMPDIR
+}
+
 # load the test helper functions like `load` or `run` that are needed to run a (preprocessed) .bats file without bash errors
 # shellcheck source=lib/bats-core/test_functions.bash disable=SC2153
 source "$BATS_ROOT/lib/bats-core/test_functions.bash"
@@ -50,42 +84,61 @@ source "$BATS_ROOT/lib/bats-core/test_functions.bash"
 source "$BATS_ROOT/lib/bats-core/tracing.bash"
 
 bats_teardown_trap() {
-  bats_error_trap
-  local status=0
+  bats_check_status_from_trap
+  local bats_teardown_trap_status=0
+
+  # `bats_teardown_trap` is always called with one parameter (BATS_TEARDOWN_STARTED)
+  # The second parameter is optional and corresponds for to the killer pid
+  # that will be forwarded to the exit trap to kill it if necesary
+  local killer_pid=${2:-}
+
   # mark the start of this function to distinguish where skip is called
   # parameter 1 will signify the reason why this function was called
   # this is used to identify when this is called as exit trap function
   BATS_TEARDOWN_STARTED=${1:-1}
-  teardown >>"$BATS_OUT" 2>&1 || status="$?"
+  teardown >>"$BATS_OUT" 2>&1 || bats_teardown_trap_status="$?"
 
-  if [[ $status -eq 0 ]]; then
+  if [[ $bats_teardown_trap_status -eq 0 ]]; then
     BATS_TEARDOWN_COMPLETED=1
   elif [[ -n "$BATS_TEST_COMPLETED" ]]; then
-    BATS_ERROR_STATUS="$status"
+    BATS_DEBUG_LAST_STACK_TRACE_IS_VALID=1
+    BATS_ERROR_STATUS="$bats_teardown_trap_status"
   fi
 
-  bats_exit_trap
+  bats_exit_trap "$killer_pid"
 }
 
+# shellcheck source=lib/bats-core/common.bash
+source "$BATS_ROOT/lib/bats-core/common.bash"
+
 bats_exit_trap() {
-  local line
   local status
-  local skipped=''
+  local exit_metadata=''
+  local killer_pid=${1:-}
   trap - ERR EXIT
+  if [[ -n "${BATS_TEST_TIMEOUT:-}" ]]; then
+    # Kill the watchdog in the case of of kernel finished before the timeout
+    bats_abort_timeout_countdown "$killer_pid" || status=1
+  fi
 
   if [[ -n "$BATS_TEST_SKIPPED" ]]; then
-    skipped=' # skip'
+    exit_metadata=' # skip'
     if [[ "$BATS_TEST_SKIPPED" != '1' ]]; then
-      skipped+=" $BATS_TEST_SKIPPED"
+      exit_metadata+=" $BATS_TEST_SKIPPED"
     fi
+  elif [[ "${BATS_TIMED_OUT-NOTSET}" != NOTSET ]]; then
+    exit_metadata=" # timeout after ${BATS_TEST_TIMEOUT}s"
   fi
 
   BATS_TEST_TIME=''
-  if [[ -z "${skipped}" && -n "$BATS_ENABLE_TIMING" ]]; then
-    BATS_TEST_TIME=" in "$(( $(get_mills_since_epoch) - BATS_TEST_START_TIME ))"ms"
+  if [[ -n "$BATS_ENABLE_TIMING" ]]; then
+    BATS_TEST_TIME=" in "$(($(get_mills_since_epoch) - BATS_TEST_START_TIME))"ms"
   fi
 
-  if [[ -z "$BATS_TEST_COMPLETED" || -z "$BATS_TEARDOWN_COMPLETED" ]]; then
+  local print_bats_out="${BATS_SHOW_OUTPUT_OF_SUCCEEDING_TESTS}"
+
+  local should_retry=''
+  if [[ -z "$BATS_TEST_COMPLETED" || -z "$BATS_TEARDOWN_COMPLETED" || "${BATS_INTERRUPTED-NOTSET}" != NOTSET ]]; then
     if [[ "$BATS_ERROR_STATUS" -eq 0 ]]; then
       # For some versions of bash, `$?` may not be set properly for some error
       # conditions before triggering the EXIT trap directly (see #72 and #81).
@@ -96,84 +149,197 @@ bats_exit_trap() {
       # If instead the test fails, and the `teardown()` error happens while
       # `bats_teardown_trap` runs as the EXIT trap, the test will fail with no
       # output, since there's no way to reach the `bats_exit_trap` call.
-      BATS_STACK_TRACE=("${BATS_CURRENT_STACK_TRACE[@]}")
       BATS_ERROR_STATUS=1
     fi
-    printf 'not ok %d %s\n' "$BATS_SUITE_TEST_NUMBER" "${BATS_TEST_DESCRIPTION}${BATS_TEST_TIME}" >&3
-    bats_print_stack_trace "${BATS_STACK_TRACE[@]}" >&3
-    bats_print_failed_command >&3
+    if bats_should_retry_test; then
+      should_retry=1
+      status=126                # signify retry
+      rm -r "$BATS_TEST_TMPDIR" # clean up for retry
+    else
+      printf 'not ok %d %s%s\n' "$BATS_SUITE_TEST_NUMBER" "${BATS_TEST_NAME_PREFIX:-}${BATS_TEST_DESCRIPTION}${BATS_TEST_TIME}" "$exit_metadata" >&3
+      local stack_trace
+      bats_get_failure_stack_trace stack_trace
+      bats_print_stack_trace "${stack_trace[@]}" >&3
+      bats_print_failed_command "${stack_trace[@]}" >&3
 
-    while IFS= read -r line; do
-      printf '# %s\n' "$line" || break # avoid feedback loop when errors are redirected into BATS_OUT (see #353)
-    done <"$BATS_OUT" >&3
-    if [[ -n "$line" ]]; then
-      printf '# %s\n' "$line"
+      if [[ $BATS_PRINT_OUTPUT_ON_FAILURE ]]; then
+        if [[ -n "${output:-}" ]]; then
+          printf "Last output:\n%s\n" "$output"
+        fi
+        if [[ -n "${stderr:-}" ]]; then
+          printf "Last stderr: \n%s\n" "$stderr"
+        fi
+      fi >>"$BATS_OUT"
+
+      print_bats_out=1
+      status=1
+      local state=failed
     fi
-    status=1
   else
-    printf 'ok %d %s%s\n' "$BATS_SUITE_TEST_NUMBER" "${BATS_TEST_DESCRIPTION}${BATS_TEST_TIME}" \
-      "$skipped" >&3
+    printf 'ok %d %s%s\n' "$BATS_SUITE_TEST_NUMBER" "${BATS_TEST_NAME_PREFIX:-}${BATS_TEST_DESCRIPTION}${BATS_TEST_TIME}" \
+      "$exit_metadata" >&3
     status=0
+    local state=passed
   fi
 
+  if [[ -z "$should_retry" ]]; then
+    printf "%s %s\t%s\n" "$state" "$BATS_TEST_FILENAME" "$BATS_TEST_NAME" >>"$BATS_RUNLOG_FILE"
+
+    if [[ $print_bats_out ]]; then
+      bats_prefix_lines_for_tap_output <"$BATS_OUT" | bats_replace_filename >&3
+    fi
+  fi
+  if [[ $BATS_GATHER_TEST_OUTPUTS_IN ]]; then
+    local try_suffix=
+    if [[ -n "$should_retry" ]]; then
+      try_suffix="-try$BATS_TEST_TRY_NUMBER"
+    fi
+    cp "$BATS_OUT" "$BATS_GATHER_TEST_OUTPUTS_IN/$BATS_SUITE_TEST_NUMBER$try_suffix-$BATS_TEST_DESCRIPTION.log"
+  fi
   rm -f "$BATS_OUT"
   exit "$status"
+}
+
+# Marks the test as failed due to timeout.
+# The actual termination of subprocesses is done via pkill in the background
+# process in bats_start_timeout_countdown
+# shellcheck disable=SC2317
+bats_timeout_trap() {
+  BATS_TIMED_OUT=1
+  BATS_DEBUG_LAST_STACK_TRACE_IS_VALID=
+  exit 1
+}
+
+bats_get_child_processes_of() { # <parent-pid>
+  local -ri parent_pid=${1?}
+  {
+    read -ra header
+    local pid_col ppid_col
+    for ((i = 0; i < ${#header[@]}; ++i)); do
+      if [[ ${header[$i]} == "PID" ]]; then
+        pid_col=$i
+      fi
+      if [[ ${header[$i]} == "PPID" ]]; then
+        ppid_col=$i
+      fi
+    done
+    while read -ra row; do
+      if ((${row[$ppid_col]} == parent_pid)); then
+        printf "%d\n" "${row[$pid_col]}"
+      fi
+    done
+  } < <(ps -ef "$parent_pid")
+}
+
+bats_kill_childprocesses_of() { # <parent-pid>
+  local -ir parent_pid="${1?}"
+  if command -v pkill; then
+    pkill -P "$parent_pid"
+  else
+    # kill in reverse order (latest first)
+    while read -r pid; do
+      kill "$pid"
+    done < <(bats_get_child_processes_of "$parent_pid" | sort -r)
+  fi >/dev/null
+}
+
+# sets a timeout for this process
+#
+# using SIGABRT for interprocess communication.
+# Ruled out:
+# USR1/2 - not available on Windows
+# SIGALRM - interferes with sleep:
+#           "sleep(3) may be implemented using SIGALRM; mixing calls to alarm()
+#           and sleep(3) is a bad idea." ~ https://linux.die.net/man/2/alarm
+bats_start_timeout_countdown() { # <timeout>
+  local -ri timeout=$1
+  local -ri target_pid=$$
+  # shellcheck disable=SC2064
+  trap "bats_timeout_trap $target_pid" ABRT
+  if ! (command -v ps || command -v pkill) >/dev/null; then
+    printf "Error: Cannot execute timeout because neither pkill nor ps are available on this system!\n" >&2
+    exit 1
+  fi
+  # Start another process to kill the children of this process
+  (
+    sleep "$timeout" &
+    # sleep won't recieve signals, so we use wait below
+    # and kill sleep explicitly when signalled to do so
+    # shellcheck disable=SC2064
+    trap "kill $!; exit 0" ABRT
+    wait
+    if kill -ABRT "$target_pid"; then
+      # get rid of signal blocking child processes (like sleep)
+      bats_kill_childprocesses_of "$target_pid"
+    fi &>/dev/null
+  ) &
+}
+
+bats_abort_timeout_countdown() {
+  # kill the countdown process, don't care if its still there
+  kill -ABRT "$1" &>/dev/null || true
 }
 
 get_mills_since_epoch() {
   local ms_since_epoch
   ms_since_epoch=$(date +%s%N)
   if [[ "$ms_since_epoch" == *N || "${#ms_since_epoch}" -lt 19 ]]; then
-        ms_since_epoch=$(( $(date +%s) * 1000 ))
+    ms_since_epoch=$(($(date +%s) * 1000))
   else
-        ms_since_epoch=$(( ms_since_epoch / 1000000 ))
+    ms_since_epoch=$((ms_since_epoch / 1000000))
   fi
 
   printf "%d\n" "$ms_since_epoch"
 }
 
 bats_perform_test() {
-  export BATS_TEST_NAME="$1"
-  export BATS_SUITE_TEST_NUMBER="$2"
-  export BATS_TEST_NUMBER="$3"
-
   if ! declare -F "$BATS_TEST_NAME" &>/dev/null; then
-    printf "bats: unknown test name \`%s'\n" "$BATS_TEST_NAME" >&2
+    local quoted_test_name
+    bats_quote_code quoted_test_name "$BATS_TEST_NAME"
+    printf "bats: unknown test name %s\n" "$quoted_test_name" >&2
     exit 1
   fi
 
-  # Some versions of Bash will reset BASH_LINENO to the first line of the
-  # function when the ERR trap fires. All versions of Bash appear to reset it
-  # on an unbound variable access error. bats_debug_trap will fire both before
-  # the offending line is executed, and when the error is triggered.
-  # Consequently, we use `BATS_CURRENT_STACK_TRACE` recorded by the
-  # first call to bats_debug_trap, _before_ the ERR trap or unbound variable
-  # access fires.
-  BATS_STACK_TRACE=()
-  BATS_CURRENT_STACK_TRACE=()
+  # is this skipped from outside ?
+  if [[ -n "${BATS_TEST_SKIPPED-}" ]]; then
+    # forward skip (with message) by overriding setup
+    # shellcheck disable=SC2317
+    setup() {
+      skip "$BATS_TEST_SKIPPED"
+    }
+  fi
 
+  local BATS_killer_pid=''
+  if [[ -n "${BATS_TEST_TIMEOUT:-}" ]]; then
+    bats_start_timeout_countdown "$BATS_TEST_TIMEOUT"
+    BATS_killer_pid=$!
+  fi
   BATS_TEST_COMPLETED=
-  BATS_TEST_SKIPPED=
+  BATS_TEST_SKIPPED=${BATS_TEST_SKIPPED-}
   BATS_TEARDOWN_COMPLETED=
   BATS_ERROR_STATUS=
-  trap 'bats_debug_trap "$BASH_SOURCE"' DEBUG
-  trap 'bats_error_trap' ERR
-  # mark this call as trap call
-  trap 'bats_teardown_trap as-exit-trap' EXIT
+  bats_setup_tracing
+  # use parameter to mark this call as trap call
+  # shellcheck disable=SC2064
+  trap "bats_teardown_trap as-exit-trap $BATS_killer_pid" EXIT
 
   BATS_TEST_START_TIME=$(get_mills_since_epoch)
-  "$BATS_TEST_NAME" >>"$BATS_OUT" 2>&1
+  "$BATS_TEST_NAME" >>"$BATS_OUT" 2>&1 4>&1
 
   BATS_TEST_COMPLETED=1
-  trap 'bats_exit_trap' EXIT
-  bats_teardown_trap "" # pass empty parameter to signify call outside trap
+  # shellcheck disable=SC2064
+  trap "bats_exit_trap $BATS_killer_pid" EXIT
+  bats_teardown_trap "" "$BATS_killer_pid" # pass empty parameter to signify call outside trap
 }
+
+trap bats_interrupt_trap INT
 
 # shellcheck source=lib/bats-core/preprocessing.bash
 source "$BATS_ROOT/lib/bats-core/preprocessing.bash"
 
 exec 3<&1
 
+bats_create_test_tmpdirs
 # Run the given test.
 bats_evaluate_preprocessed_source
-bats_perform_test "$@"
+bats_perform_test
diff --git a/libexec/bats-core/bats-format-junit b/libexec/bats-core/bats-format-junit
--- a/libexec/bats-core/bats-format-junit
+++ b/libexec/bats-core/bats-format-junit
@@ -1,25 +1,16 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
+# shellcheck source=lib/bats-core/formatter.bash
+source "$BATS_ROOT/lib/bats-core/formatter.bash"
+
 BASE_PATH=.
 
 while [[ "$#" -ne 0 ]]; do
   case "$1" in
-    --base-path)
-      shift
-      # the relative path root to use for reporting filenames
-      # this is mainly intended for suite mode, where this will be the suite root folder
-      BASE_PATH="$1"
-      # use the containing directory when --base-path is a file
-      if [[ ! -d "$BASE_PATH" ]]; then
-        BASE_PATH="$(dirname "$BASE_PATH")"
-      fi
-      # get the absolute path
-      BASE_PATH="$(cd "$BASE_PATH"; pwd)"
-      # ensure the path ends with / to strip that later on
-      if [[ "${BASE_PATH}" != *"/" ]]; then
-        BASE_PATH="$BASE_PATH/"
-      fi
+  --base-path)
+    shift
+    normalize_base_path BASE_PATH "$1"
     ;;
   esac
   shift
@@ -27,7 +18,7 @@ done
 
 init_suite() {
   suite_test_exec_time=0
-  # since we have to print the suite header before its contents but we don't know the contents before the header, 
+  # since we have to print the suite header before its contents but we don't know the contents before the header,
   # we have to buffer the contents
   _suite_buffer=""
   test_result_state="" # declare for the first flush, when no test has been encountered
@@ -40,6 +31,7 @@ init_file() {
   file_skipped=0
   file_exec_time=0
   test_exec_time=0
+  name=""
   _buffer=""
   _buffer_log=""
   _system_out_log=""
@@ -75,7 +67,7 @@ suite_header() {
 file_header() {
   timestamp=$(date -u +"%Y-%m-%dT%H:%M:%S")
   printf "<testsuite name=\"%s\" tests=\"%s\" failures=\"%s\" errors=\"0\" skipped=\"%s\" time=\"%s\" timestamp=\"%s\" hostname=\"%s\">\n" \
-                     "$(xml_escape "${class}")" "${file_count}" "${file_failures}" "${file_skipped}" "$(milliseconds_to_seconds "${file_exec_time}")" "${timestamp}" "$(host)"
+    "$(xml_escape "${class}")" "${file_count}" "${file_failures}" "${file_skipped}" "$(milliseconds_to_seconds "${file_exec_time}")" "${timestamp}" "$(host)"
 }
 
 file_footer() {
@@ -106,19 +98,22 @@ print_test_case() {
 }
 
 xml_escape() {
-  output=${1//&/&amp;}
-  output=${output//</&lt;}
-  output=${output//>/&gt;}
-  output=${output//'"'/&quot;}
-  output=${output//\'/&#39;}
+  output=${1//&/\&amp;}
+  output=${output//</\&lt;}
+  output=${output//>/\&gt;}
+  output=${output//'"'/\&quot;}
+  output=${output//\'/\&#39;}
   local CONTROL_CHAR=$'\033'
-  output="${output//$CONTROL_CHAR/&#27;}"
+  output=${output//$CONTROL_CHAR/\&#27;}
   printf "%s" "$output"
 }
 
 suite_buffer() {
   local output
-  output="$("$@"; printf "x")" # use x marker to avoid losing trailing newlines
+  output="$(
+    "$@"
+    printf "x"
+  )" # use x marker to avoid losing trailing newlines
   _suite_buffer="${_suite_buffer}${output%x}"
 }
 
@@ -129,7 +124,10 @@ suite_flush() {
 
 buffer() {
   local output
-  output="$("$@"; printf "x")" # use x marker to avoid losing trailing newlines
+  output="$(
+    "$@"
+    printf "x"
+  )" # use x marker to avoid losing trailing newlines
   _buffer="${_buffer}${output%x}"
 }
 
@@ -180,15 +178,13 @@ finish_suite() {
   suite_footer
 }
 
-# shellcheck source=lib/bats-core/formatter.bash
-source "$BATS_ROOT/lib/bats-core/formatter.bash"
-
 bats_tap_stream_plan() { #  <number of tests>
   :
 }
 
 init_suite
 trap finish_suite EXIT
+trap '' INT
 
 bats_tap_stream_begin() { # <test index> <test name>
   flush_log
@@ -196,12 +192,8 @@ bats_tap_stream_begin() { # <test index> <test name>
   name="$2"
 }
 
-bats_tap_stream_ok() { # [--duration <milliseconds] <test index> <test name>
-  if [[ "$1" == "--duration" ]]; then
-    test_exec_time="${BASH_REMATCH[1]}"
-  else
-    test_exec_time=0
-  fi
+bats_tap_stream_ok() { # <test index> <test name>
+  test_exec_time=${BATS_FORMATTER_TEST_DURATION:-0}
   ((file_count += 1))
   test_result_state='ok'
   file_exec_time="$((file_exec_time + test_exec_time))"
@@ -209,6 +201,7 @@ bats_tap_stream_ok() { # [--duration <milliseconds] <test index> <test name>
 }
 
 bats_tap_stream_skipped() { # <test index> <test name> <skip reason>
+  test_exec_time=${BATS_FORMATTER_TEST_DURATION:-0}
   ((file_count += 1))
   ((file_skipped += 1))
   test_result_state='skipped'
@@ -216,34 +209,38 @@ bats_tap_stream_skipped() { # <test index> <test name> <skip reason>
   test_skip_message="$3"
 }
 
-bats_tap_stream_not_ok() { # [--duration <milliseconds>] <test index> <test name>
+bats_tap_stream_not_ok() { # <test index> <test name>
+  test_exec_time=${BATS_FORMATTER_TEST_DURATION:-0}
   ((file_count += 1))
   ((file_failures += 1))
-  if [[ "$1" == "--duration" ]]; then
-    test_exec_time="${BASH_REMATCH[1]}"
-  else
-    test_exec_time=0
-  fi
   test_result_state=not_ok
   file_exec_time="$((file_exec_time + test_exec_time))"
   suite_test_exec_time=$((suite_test_exec_time + test_exec_time))
 }
 
 bats_tap_stream_comment() { # <comment text without leading '# '> <scope>
-  if [[ "$2" == begin ]]; then
+  local comment="$1" scope="$2"
+  case "$scope" in
+  begin)
     # everything that happens between begin and [not] ok is FD3 output from the test
-    log_system_out "$1"
-  else
+    log_system_out "$comment"
+    ;;
+  ok)
+    # non failed tests can produce FD3 output
+    log_system_out "$comment"
+    ;;
+  *)
     # everything else is considered error output
     log "$1"
-  fi
+    ;;
+  esac
 }
 
 bats_tap_stream_suite() { # <file name>
   flush_log
   suite_buffer finish_file
   init_file
-  class="$(remove_prefix "$BASE_PATH" "$1")"
+  class="${1/$BASE_PATH/}"
 }
 
 bats_tap_stream_unknown() { # <full line>
diff --git a/libexec/bats-core/bats-format-pretty b/libexec/bats-core/bats-format-pretty
--- a/libexec/bats-core/bats-format-pretty
+++ b/libexec/bats-core/bats-format-pretty
@@ -1,10 +1,20 @@
 #!/usr/bin/env bash
 set -e
 
+# shellcheck source=lib/bats-core/formatter.bash
+source "$BATS_ROOT/lib/bats-core/formatter.bash"
+
+BASE_PATH=.
+BATS_ENABLE_TIMING=
+
 while [[ "$#" -ne 0 ]]; do
   case "$1" in
   -T)
     BATS_ENABLE_TIMING="-T"
+    ;;
+  --base-path)
+    shift
+    normalize_base_path BASE_PATH "$1"
     ;;
   esac
   shift
@@ -30,10 +40,18 @@ update_count_column_left() {
   count_column_left=$((screen_width - count_column_width))
 }
 
-trap update_screen_width WINCH
+# avoid unset variables
+count=0
+screen_width=80
+update_count_column_width
 update_screen_width
+test_result=
+
+trap update_screen_width WINCH
 
 begin() {
+  test_result= # reset to avoid carrying over result state from previous test
+  line_backoff_count=0
   go_to_column 0
   update_count_column_width
   buffer_with_truncation $((count_column_left - 1)) '   %s' "$name"
@@ -47,44 +65,79 @@ begin() {
   go_to_column 1
 }
 
-pass() {
+finish_test() {
+  move_up $line_backoff_count
   go_to_column 0
-  buffer ' ✓ %s' "$name"
-  if [[ -n "$BATS_ENABLE_TIMING" ]]; then
+  buffer "$@"
+  if [[ -n "${TIMEOUT-}" ]]; then
     set_color 2
-    buffer ' [%s]' "$1"
+    if [[ -n "$BATS_ENABLE_TIMING" ]]; then
+      buffer ' [%s (timeout: %s)]' "$TIMING" "$TIMEOUT"
+    else
+      buffer ' [timeout: %s]' "$TIMEOUT"
+    fi
+  else
+    if [[ -n "$BATS_ENABLE_TIMING" ]]; then
+      set_color 2
+      buffer ' [%s]' "$TIMING"
+    fi
   fi
   advance
+  move_down $((line_backoff_count - 1))
+}
+
+pass() {
+  local TIMING="${1:-}"
+  finish_test ' ✓ %s' "$name"
+  test_result=pass
 }
 
 skip() {
-  local reason="$1"
+  local reason="$1" TIMING="${2:-}"
   if [[ -n "$reason" ]]; then
     reason=": $reason"
   fi
-  go_to_column 0
-  buffer ' - %s (skipped%s)' "$name" "$reason"
-  advance
+  finish_test ' - %s (skipped%s)' "$name" "$reason"
+  test_result=skip
 }
 
 fail() {
-  go_to_column 0
+  local TIMING="${1:-}"
   set_color 1 bold
-  buffer ' ✗ %s' "$name"
-  if [[ -n "$BATS_ENABLE_TIMING" ]]; then
-    set_color 2
-    buffer ' [%s]' "$1"
-  fi
-  advance
+  finish_test ' ✗ %s' "$name"
+  test_result=fail
+}
+
+timeout() {
+  local TIMING="${1:-}"
+  set_color 3 bold
+  TIMEOUT="${2:-}" finish_test ' ✗ %s' "$name"
+  test_result=timeout
 }
 
 log() {
-  set_color 1
+  case ${test_result} in
+  pass)
+    clear_color
+    ;;
+  fail)
+    set_color 1
+    ;;
+  timeout)
+    set_color 3
+    ;;
+  esac
   buffer '   %s\n' "$1"
   clear_color
 }
 
 summary() {
+  if [ "$failures" -eq 0 ]; then
+    set_color 2 bold
+  else
+    set_color 1 bold
+  fi
+
   buffer '\n%d test' "$count"
   if [[ "$count" -ne 1 ]]; then
     buffer 's'
@@ -99,7 +152,11 @@ summary() {
     buffer ', %d skipped' "$skipped"
   fi
 
-  not_run=$((count - passed - failures - skipped))
+  if ((timed_out > 0)); then
+    buffer ', %d timed out' "$timed_out"
+  fi
+
+  not_run=$((count - passed - failures - skipped - timed_out))
   if [[ "$not_run" -gt 0 ]]; then
     buffer ', %d not run' "$not_run"
   fi
@@ -109,6 +166,7 @@ summary() {
   fi
 
   buffer '\n'
+  clear_color
 }
 
 buffer_with_truncation() {
@@ -123,6 +181,18 @@ buffer_with_truncation() {
     buffer '%s...' "${string:0:$((width - 4))}"
   else
     buffer '%s' "$string"
+  fi
+}
+
+move_up() {
+  if [[ $1 -gt 0 ]]; then # avoid moving if we got 0
+    buffer '\x1B[%dA' "$1"
+  fi
+}
+
+move_down() {
+  if [[ $1 -gt 0 ]]; then # avoid moving if we got 0
+    buffer '\x1B[%dB' "$1"
   fi
 }
 
@@ -145,7 +215,7 @@ set_color() {
   local color="$1"
   local weight=22
 
-  if [[ "$2" == 'bold' ]]; then
+  if [[ "${2:-}" == 'bold' ]]; then
     weight=1
   fi
   buffer '\x1B[%d;%dm' "$((30 + color))" "$weight"
@@ -164,6 +234,13 @@ buffer() {
   _buffer+="$content"
 }
 
+prefix_buffer_with() {
+  local old_buffer="$_buffer"
+  _buffer=''
+  "$@"
+  _buffer="$_buffer$old_buffer"
+}
+
 flush() {
   printf '%s' "$_buffer"
   _buffer=
@@ -175,9 +252,7 @@ finish() {
 }
 
 trap finish EXIT
-
-# shellcheck source=lib/bats-core/formatter.bash
-source "$BATS_ROOT/lib/bats-core/formatter.bash"
+trap '' INT
 
 bats_tap_stream_plan() {
   count="$1"
@@ -185,6 +260,7 @@ bats_tap_stream_plan() {
   passed=0
   failures=0
   skipped=0
+  timed_out=0
   name=
   update_count_column_width
 }
@@ -195,39 +271,76 @@ bats_tap_stream_begin() {
   begin
   flush
 }
-  
+
 bats_tap_stream_ok() {
   index="$1"
+  name="$2"
   ((++passed))
-  if [[ "$1" == "--duration" ]]; then
-    pass "$2"
-  else
-    pass
-  fi
+
+  pass "${BATS_FORMATTER_TEST_DURATION:-}"
 }
 
 bats_tap_stream_skipped() {
   index="$1"
+  name="$2"
   ((++skipped))
-  skip "$3"
+  skip "$3" "${BATS_FORMATTER_TEST_DURATION:-}"
 }
 
 bats_tap_stream_not_ok() {
   index="$1"
-  ((++failures))
-  if [[ "$1" == "--duration" ]]; then
-    fail "$2"
+  name="$2"
+
+  if [[ ${BATS_FORMATTER_TEST_TIMEOUT-x} != x ]]; then
+    timeout "${BATS_FORMATTER_TEST_DURATION:-}" "${BATS_FORMATTER_TEST_TIMEOUT}s"
+    ((++timed_out))
   else
-    fail
+    fail "${BATS_FORMATTER_TEST_DURATION:-}"
+    ((++failures))
   fi
+
 }
 
-bats_tap_stream_comment() {
+bats_tap_stream_comment() { # <comment> <scope>
+  local scope=$2
+  # count the lines we printed after the begin text,
+  if [[ $line_backoff_count -eq 0 && $scope == begin ]]; then
+    # if this is the first line after begin, go down one line
+    buffer "\n"
+    ((++line_backoff_count)) # prefix-increment to avoid "error" due to returning 0
+  fi
+
+  ((++line_backoff_count))
+  ((line_backoff_count += ${#1} / screen_width)) # account for linebreaks due to length
   log "$1"
 }
 
 bats_tap_stream_suite() {
-  : #test_file="$1"
+  #test_file="$1"
+  line_backoff_count=0
+  index=
+  # indicate filename for failures
+  local file_name="${1#"$BASE_PATH"}"
+  name="File $file_name"
+  set_color 4 bold
+  buffer "%s\n" "$file_name"
+  clear_color
+}
+
+line_backoff_count=0
+bats_tap_stream_unknown() { # <full line> <scope>
+  local scope=$2
+  # count the lines we printed after the begin text, (or after suite, in case of syntax errors)
+  if [[ $line_backoff_count -eq 0 && ($scope == begin || $scope == suite) ]]; then
+    # if this is the first line after begin, go down one line
+    buffer "\n"
+    ((++line_backoff_count)) # prefix-increment to avoid "error" due to returning 0
+  fi
+
+  ((++line_backoff_count))
+  ((line_backoff_count += ${#1} / screen_width)) # account for linebreaks due to length
+  buffer "%s\n" "$1"
+  flush
 }
 
 bats_parse_internal_extended_tap
